export const resList = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "499254",
        name: "La Pino'z Pizza",
        uuid: "27391e3a-4118-4ea1-a3fb-6ab05e617672",
        city: "5",
        area: "Virar",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "5fe4444a065b60c4fe39ef975222c12b",
        cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 6.199999809265137,
        slugs: {
          restaurant: "la-pinon-z-pizza-virar-virar",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop No. 3,4, Cosmos Square, Global City, Chikhal Dongari Road,, Virar West, Maharashtra 401303",
        locality: "Global City",
        parentId: 4961,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 8200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8200,
          message: "",
          title: "Delivery Charge",
          amount: "8200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7213357~p=1~eid=00000189-50bd-1c58-0595-a2c100d90177~srvts=1689276718168",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "499254",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 6.199999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.8",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "112497",
        name: "Saikripa Restaurant",
        uuid: "d8965e35-2e79-4363-930d-af2f4b5b4a54",
        city: "5",
        area: "Nalasopara East",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "hntaoddjfjuzmdwxlcxb",
        cuisines: ["Chinese"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 3.700000047683716,
        slugs: {
          restaurant: "sai-kripa-chinese-cusine-nalasopara-nala-sopara",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Sai Kripa Chinese Cusine, 23, Martin Commercial Complex, Nallasopara Vasai Link Road, Nalasopara, Mumbai",
        locality: "Nalasopara East",
        parentId: 175651,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹999",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "112497",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 3.700000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "81699",
        name: "Parathas & Biryani",
        uuid: "d4e16fb7-25d7-4f7b-991a-8379b6c39d3b",
        city: "5",
        area: "Palghar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "eabbtmoriwckpa7xzqgm",
        cuisines: ["North Indian", "Biryani"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 2.9000000953674316,
        slugs: {
          restaurant: "parathas-biryani-virar-west-virar",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Flat 7J/2105 Mhada Complex, Nallasopara Link Road,Near Tree House High School, Virar West , Vasai Virar Municipal Corporation - Zone C, Palghar, Maharashtra - 401303",
        locality: "Virar West",
        parentId: 155490,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3900,
          message: "",
          title: "Delivery Charge",
          amount: "3900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "81699",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 2.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.0",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "696246",
        name: "GetAWay-Desserts",
        uuid: "15800e0a-009b-4aec-8069-f44bf3ba4ee1",
        city: "5",
        area: "Cosmos Square",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "2e93c40100a50e4bfabce89c35154ec6",
        cuisines: ["Ice Cream", "Desserts", "Healthy Food"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 6.199999809265137,
        slugs: {
          restaurant: "getaway-desserts-virar-virar",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop No.F-30/B, 1st Floor, Cosmos Square, Chikhal Dongri Road, Virar (West), Vasai Virar Municipal Corporation - Zone A, Palghar, , Maharashtra, 401303",
        locality: "Virar",
        parentId: 354819,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 8200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8200,
          message: "",
          title: "Delivery Charge",
          amount: "8200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7391638~p=4~eid=00000189-50bd-1c58-0595-a2c200d90441~srvts=1689276718168",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "696246",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 6.199999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "--",
        totalRatings: 0,
        new: true,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "77213",
        name: "Uwiee's Burger, Fries & More",
        uuid: "54442049-3492-4e4c-8026-420346544369",
        city: "5",
        area: "Nalasopara East",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "zu8pij9ybjdftntberhk",
        cuisines: ["American"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "uwiees-burger-fries-more-nalasopara-nala-sopara",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop No 9, Kanti Avenue, Opp The Capital Mall Gate No.3 Nallasopara East",
        locality: "Nalasopara East",
        parentId: 220542,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "77213",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "234113",
        name: "Star Rolls & More",
        uuid: "3c43eb13-abdd-4c6b-a94d-7884ec621019",
        city: "5",
        area: "Vasai East",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "h2yhbfxs22woc13zrphe",
        cuisines: ["Indian", "Snacks", "North Indian", "Kebabs"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 44,
        minDeliveryTime: 44,
        maxDeliveryTime: 44,
        slaString: "44 MINS",
        lastMileTravel: 3.700000047683716,
        slugs: {
          restaurant: "star-frankie-vasai-vasai",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "C-003, Jivdani Complex, Near Santoshi Mata Mandir, Deendayal Upadhyay Road, Behind Swamini Bunglow Nalasopara East, Vasai Virar Municipal Corporation - Zone B, Palghar, Maharashtra - 401209",
        locality: "Vasai",
        parentId: 316578,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "234113",
          deliveryTime: 44,
          minDeliveryTime: 44,
          maxDeliveryTime: 44,
          lastMileTravel: 3.700000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "540984",
        name: "Momos Station",
        uuid: "ff8382c4-70d1-4704-bc0d-6755ffd88015",
        city: "5",
        area: "Virar",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "edunkwugshwqlsv2hdxt",
        cuisines: ["Chinese", "Fast Food"],
        tags: [],
        costForTwo: 45000,
        costForTwoString: "₹450 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 6.400000095367432,
        slugs: {
          restaurant: "momos-station-virar-virar",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "SHOP NO 13, SHREE SHASHWAT Building NO-4,block sector GLOBAL CITY,VIRAR WEST, Vasai Tahashil, Palghar Zone 2, Maharashtra - 401303",
        locality: "Block Sector Global City",
        parentId: 138441,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 8200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8200,
          message: "",
          title: "Delivery Charge",
          amount: "8200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7411969~p=7~eid=00000189-50bd-1c58-0595-a2c300d9071a~srvts=1689276718168",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "540984",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 6.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "169429",
        name: "House Of Rolls",
        uuid: "4dfcb571-7b8f-4fd0-94f9-ad2038298495",
        city: "5",
        area: "Vasai",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "gm9cme5nkerlc55difd5",
        cuisines: ["Street Food"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 3.700000047683716,
        slugs: {
          restaurant: "star-frankie-vashi",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "C-003, Jivdani Complex, Near Mauli Washing Centre, Deendayal Upadhyay Road, Behind Swamini Bunglow Nalasopara East , Vasai Virar Municipal Corporation - Zone B, Palghar, Maharashtra - 401209",
        locality: "Nalasopara East",
        parentId: 313231,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "169429",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 3.700000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.0",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "365614",
        name: "Bharka Devi Ice Cream",
        uuid: "9f9a9647-2594-4b1f-80c5-2bd3f3b863ac",
        city: "5",
        area: "Nalasopara East",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "toyl9p8brpw1oeiyvwly",
        cuisines: ["Beverages", "Ice Cream"],
        tags: [],
        costForTwo: 10000,
        costForTwoString: "₹100 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 3.799999952316284,
        slugs: {
          restaurant: "bharkadevi-icecream-vasai-vasai",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop no 11,saidesp plaza,yashwant viva township,near nkgsb bank,nallasopara east,taluka vasai,district palghar,pincode 401209",
        locality: "Vasai",
        parentId: 387350,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "365614",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 3.799999952316284,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "548634",
        name: "Eazy Bite",
        uuid: "65f6ee0d-6197-4599-8495-886a7d9fc303",
        city: "5",
        area: "Vasai",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "tvibgpiqqw4cywe1yfro",
        cuisines: ["Fast Food", "Snacks", "Arabian", "Beverages"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 3.799999952316284,
        slugs: {
          restaurant: "eazy-bite-vasai-vasai",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "C-003, Jivdani Complex, Near Mauli Washing Centre, Deendayal Upadhyay Road, Behind Swamini Bunglow Nalasopara East , Vasai Virar Municipal Corporation - Zone B, Palghar, Maharashtra-401209",
        locality: "Near Mauli Washing Centre",
        parentId: 329796,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "548634",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 3.799999952316284,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.3",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "525810",
        name: "Mustang Asian Chinese Momos Thai",
        uuid: "ebfe2763-5302-43dd-b8c0-e71d27ffc246",
        city: "5",
        area: "Nala Sopara",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "z9b3jmoibgplivho0ep7",
        cuisines: ["Chinese"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 3.5999999046325684,
        slugs: {
          restaurant: "mustang-asian-chinese-momos-thai-nala-sopara-nala-sopara",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop 6, Rashmi Lake View, Near Vinayak Hospital, Achole Road, Nalasopara, Mumbai",
        locality: "Vinayak Hospital",
        parentId: 316122,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "525810",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 3.5999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "682987",
        name: "Unshakeable",
        uuid: "8b91c335-39f6-49ec-91a5-5e028c1a3024",
        city: "5",
        area: "Virar",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "9a4762b0a6b75949c19354ed3c9ee83d",
        cuisines: ["Beverages"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 3.9000000953674316,
        slugs: {
          restaurant: "unshakeable-virar-virar",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "SHOP NO 4 BUILDING NO 1 MHADA COLONY VIRAR NALLASOPARA LINK ROAD VIRAR WEST, Vasai Virar Municipal Corporation - Zone A, Palghar, Maharashtra - 401303",
        locality: "Virar Nallasopara Link Road",
        parentId: 397535,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "682987",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 3.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "60799",
        name: "99 Pancakes",
        uuid: "1e5d602c-57ed-4a14-9dc4-69fd1821159c",
        city: "5",
        area: "Virar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "c2f533ee4960991a29227a27f516c59b",
        cuisines: ["Desserts", "Beverages"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 4.199999809265137,
        slugs: {
          restaurant: "99-pancakes-viva-college-virar",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop no.14, Prathamesh Plaza, near Natural Ice Cream, opp Hotel on the way, Agashi road, Virar (W) - 401303",
        locality: " Agashi road",
        parentId: 387975,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 5500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5500,
          message: "",
          title: "Delivery Charge",
          amount: "5500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "60799",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 4.199999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "683002",
        name: "Charcoal Burgers",
        uuid: "38fb49c7-4c92-459b-8072-f2d1c2f56082",
        city: "5",
        area: "Virar",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "126220f2c570df2211cb5a46d45f9891",
        cuisines: ["Burgers"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 3.9000000953674316,
        slugs: {
          restaurant: "charcoal-burgers-virar-virar",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "SHOP NO 4 BUILDING NO 1 MHADA COLONY VIRAR NALLASOPARA LINK ROAD VIRAR WEST, Vasai Virar Municipal Corporation - Zone A, Palghar, Maharashtra - 401303",
        locality: "Nallasopara Link Road",
        parentId: 386443,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "683002",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 3.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "682988",
        name: "Masala Maar Ke",
        uuid: "a2ea8789-c37d-4e7c-8072-11014fb58602",
        city: "5",
        area: "Virar",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "08f0c909fbfade1ecd84d7c39de8099b",
        cuisines: ["Chinese", "Kebabs", "Biryani"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 3.9000000953674316,
        slugs: {
          restaurant: "masala-maarke-virar-virar",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "SHOP NO 4 BUILDING NO 1 MHADA COLONY VIRAR NALLASOPARA LINK ROAD VIRAR WEST, Vasai Virar Municipal Corporation - Zone A, Palghar, Maharashtra - 401303",
        locality: "Virar Nallasopara Link Road",
        parentId: 133040,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4700,
          message: "",
          title: "Delivery Charge",
          amount: "4700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "682988",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 3.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
  ];
  